name: FitStrive Server
on:
  push:
    branches:
      - main

jobs:
  Update-Server:
    runs-on: self-hosted
  
    steps:
      - name: Checkout server directory
        uses: actions/checkout@v6

      - name: Build docker image
        run: |
          docker build -t fitstrive/server:latest ./server

      - name: Reboot docker containers
        run: |
          docker compose down || true
          docker compose up -d

      - name: Verify containers
        run: docker ps
