name: FitStrive Server
on:
  push:
    branches:
      - main

jobs:
  Update-Server:
    runs-on: self-hosted
  
    steps:
      - name: Checkout server directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            server
          sparse-checkout-cone-mode: true
          path: server
          
      - name: Deploy
        run: |
          pwd
          ls -la
          echo "Prepping server for deployment!"
          npm ci
          npm run build
          pm2 restart fitstrive-server
