name: FitStrive Server
on:
  push:
    branches:
      - main

jobs:
  Update-Server:
    runs-on: self-hosted
  
    steps:
      - name: Checkout server directory
        uses: actions/checkout@v6

      - name: Stop existing containers
        run: docker compose down || true
      
      - name: Build and start services
        run: docker compose up -d --build

      - name: Show running containers
        run: docker ps
